### ISSUE TITLE
Crash on Dashboard

### ISSUE THREAD

**Issue by Abdulmanan475** [BilalZurmati/News-App#2]
FATAL EXCEPTION: main
                                                                                                    Process: com.zurmati.newsapp, PID: 23895
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:611)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019) 
                                                                                                    Caused by: java.text.ParseException: Unparseable date: "2023-08-20T09:22:22.2646453Z"
                                                                                                    	at java.text.DateFormat.parse(DateFormat.java:389)
                                                                                                    	at com.zurmati.newsapp.viewmodel.DataViewModel$fetchTopHeadlinesFrom$1$1$1$onResponse$$inlined$sortedBy$1.compare(Comparisons.kt:332)
                                                                                                    	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
                                                                                                    	at java.util.TimSort.sort(TimSort.java:220)
                                                                                                    	at java.util.Arrays.sort(Arrays.java:1427)
                                                                                                    	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:2557)
                                                                                                    	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:1075)
                                                                                                    	at com.zurmati.newsapp.viewmodel.DataViewModel$fetchTopHeadlinesFrom$1$1$1.onResponse(DataViewModel.kt:94)
                                                                                                    	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
                                                                                                    	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:204)
                                                                                                    	at android.os.Looper.loop(Looper.java:291)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8129)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019) 
                                                                                                    	
Above is the crash log where app is crashed

**Step to produce**

-  Start the app
-  Authentication screen appears
-  Swap your enrolled finger on sensor 
- Authenticated successfully
- App crashed

**Expected behavior**
-  Start the app
-  Authentication screen appears
-  Swap your enrolled finger on sensor 
- Authenticated successfully
- Navigate to dashboard and show latest news

**Comment by BilalZurmati** [comment]
resolved, now its working fine.
